### ISSUE TITLE
Refine Vega visualization

### ISSUE THREAD

**Issue by theodore-s-beers** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#468]
@XeniaMonika, I finally got a proof of concept working:

https://m-l-d-h.github.io/Closing-The-Gap-In-Non-Latin-Script-Data/vis/

I'll spare you the details here, but I had to try several different approaches. It was maddening. I hope the end result makes sense to you. I didn't change much in the `VisualizationSpec` that you were already using, and as for the data files, I just copied them. You'll see what I mean when you look at the component code.

From this working starting point, we should be able to make improvements, n'est-ce pas? We can talk about this at our next meeting.

**Comment by XeniaMonika** [comment]
Wow, that´s amazing! Thank you, I´ll have a look at it towards the end of the week and finalize the details

**Comment by XeniaMonika** [comment]
I´m preparing our data for the visualization and I have realized that it would be more convenient to have a new data entry called `category` with four options: `digital_preservation`, `infrastructure`, `tools_and_analysis` and `other`. It will make the code for the vis way easier. I know it is not a perfect solution since these categories are not 100% consistent but we can still discuss which options make the most sense later.  I wouldn´t make it visible in the frontend though. So would you mind if I changed the schema?

**Comment by XeniaMonika** [comment]
I have also put the vis on the website already. I have also added a TS file to the *vis' route folder for data management, it´s not ready yet. If there is a better way put do it, let me know. I could also do it the component directly

**Comment by theodore-s-beers** [comment]
> it would be more convenient to have a new data entry called `category` with four options: `digital_preservation`, `infrastructure`, `tools_and_analysis` and `other`

Wasn't it that way before? Categories and keywords used to be separate. Anyway, we could go back to that.
